name = "cloudflare-shop-ai"
main = "src/entry.py"
compatibility_date = "2026-10-05"
compatibility_flags = ["python_workers"]

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "cloudflare-shop-db"
database_id = "9fbc7a51-f944-487f-a0f6-a8fbfad76b0a"

[observability]
enabled = true
